### ISSUE TITLE
Contacts Technologies

### ISSUE THREAD

**Issue by FranciscoGrilo** [jmamarques/curriculum#15]

**Comment by FranciscoGrilo** [comment]
Are you still doing this page?
I've assigned this 1 week ago.
Best regards

**Comment by jmamarques** [comment]
Yes, I'm working on it, my estimation is 4 days plus

**Comment by FranciscoGrilo** [comment]
Hello.
Your Estimation ends tomorrow.
Hopefully we will close the issue tomorrow.
Best Regards
