### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by jmamarques** [jmamarques/curriculum#31]

**Comment by FranciscoGrilo** [comment]
Urgent!!

**Comment by FranciscoGrilo** [comment]
Urgent!!

**Comment by FranciscoGrilo** [comment]
Need this asap

**Comment by jmamarques** [comment]
tomorrow !

**Comment by jmamarques** [comment]
The changes were made.
They will be available in next pull request to master.
Thank you in advance for your patience

JMA
